// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
	schema: "prisma/schema.prisma",
	migrations: {
		path: "prisma/migrations",
	},
	datasource: {
		url: env("DATABASE_URL"),
		// Supabase ローカル環境では directUrl は不要
		// 本番環境で接続プーリングを使う場合は shadowDatabaseUrl を検討
	},
});
